// Generates the PassIt profile picture: a 1:1 PNG with square corners, as the
// OKX review checklist requires ("PFP is 1:1, no curved corners").
//
// Written as raw PNG chunks + zlib so there is no native image dependency —
// it runs anywhere Node runs. Emits brand/passit-pfp.png and src/brand.ts.
import { deflateSync } from "node:zlib";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

const SIZE = 512;
const BG: RGB = [0x1e, 0x40, 0xaf]; // brand deep blue
const FG: RGB = [0xff, 0xff, 0xff];

type RGB = [number, number, number];
interface Rect { x0: number; y0: number; x1: number; y1: number }

/** A bold geometric "P" — legible down to ~32px in the marketplace grid. */
const GLYPH: Rect[] = [
  { x0: 161, y0: 110, x1: 231, y1: 402 }, // stem
  { x0: 231, y0: 110, x1: 351, y1: 180 }, // top bar
  { x0: 281, y0: 110, x1: 351, y1: 300 }, // bowl right
  { x0: 231, y0: 230, x1: 351, y1: 300 }, // bowl bottom
];

function render(): Buffer {
  // One filter byte (0 = none) per scanline, then RGB triples.
  const stride = SIZE * 3 + 1;
  const raw = Buffer.alloc(stride * SIZE);

  for (let y = 0; y < SIZE; y++) {
    const rowStart = y * stride;
    raw[rowStart] = 0;
    for (let x = 0; x < SIZE; x++) {
      const inGlyph = GLYPH.some((r) => x >= r.x0 && x < r.x1 && y >= r.y0 && y < r.y1);
      const [r, g, b] = inGlyph ? FG : BG;
      const p = rowStart + 1 + x * 3;
      raw[p] = r;
      raw[p + 1] = g;
      raw[p + 2] = b;
    }
  }

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(SIZE, 0);
  ihdr.writeUInt32BE(SIZE, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // colour type: truecolour RGB
  ihdr[10] = 0; // deflate
  ihdr[11] = 0; // adaptive filtering
  ihdr[12] = 0; // no interlace

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

function chunk(type: string, data: Buffer): Buffer {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body), 0);
  return Buffer.concat([len, body, crc]);
}

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(buf: Buffer): number {
  let c = 0xffffffff;
  for (const byte of buf) c = CRC_TABLE[(c ^ byte) & 0xff]! ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

const png = render();

mkdirSync(resolve(ROOT, "brand"), { recursive: true });
writeFileSync(resolve(ROOT, "brand/passit-pfp.png"), png);

writeFileSync(
  resolve(ROOT, "src/brand.ts"),
  `// Generated by scripts/make-pfp.ts — do not edit by hand.\n` +
    `// 1:1 PNG with square corners, served at /brand/pfp.png so ASP registration\n` +
    `// always has a public avatar URL available.\n` +
    `export const PASSIT_PFP_PNG = Buffer.from(\n  "${png.toString("base64")}",\n  "base64",\n);\n`,
);

console.log(`wrote brand/passit-pfp.png (${SIZE}x${SIZE}, ${png.length.toLocaleString()} bytes)`);
console.log("wrote src/brand.ts");
